openapi: 3.0.1
security: []
info:
  title: UANATACA SIGNCLOUD API DOCUMENTATION
  version: "1.0"
  x-logo:
    url: https://raw.githubusercontent.com/UANATACA/SIGNCLOUD-REPO/main/img/signcloud-logo.png?token=ATF574Q6J3IHLUQAKRVUDVDALW6B6
    altText: Signcloud logo
servers:
- url: https://cryptoapi.sandbox.uanataca.com
- url: https://cryptoapi.uanataca.com
tags:
- name: Token
  description: Token management
- name: RSA
  description: RSA key management
paths:
  /api/verify_pin:
    post:
      operationId: verify_pin
      tags:
      - Token
      summary: VERIFY PIN
      description: Verifies if the specified PIN is valid.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
        required: false
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: true
                error: null
        "401":
          description: Invalid Credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Invalid credentials
                  code: 401
                  error_code: 1
                  details: ""
        "403":
          description: "Invalid `username` or `pin` , User locked"
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Token not found
                  code: 403
                  error_code: 2
                  details: ""
        "412":
          description: Missing parameter in JSON object
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Missing parameter
                  code: 412
                  error_code: 6
                  details: password
        "420":
          description: Authentication refused (after 3 failed attempts)
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Authentication refused
                  code: 420
                  error_code: 5
                  details: "Last authentication attempt failed, next attempt will\
                    \ be accepted in 52 seconds"

  /api/change_pin:
    post:
      operationId: change_pin
      tags:
      - Token
      summary: CHANGE PIN
      description: Changes a token PIN.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials_changepin'
        required: false
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: true
                error: null
        "401":
          description: Invalid password
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Invalid credentials
                  code: 401
                  error_code: 1
                  details: ""
        "403":
          description: "Invalid `username` or `pin` , User locked"
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Token not found
                  code: 403
                  error_code: 2
                  details: ""
        "412":
          description: Missing parameter in JSON object
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Missing parameter
                  code: 412
                  error_code: 6
                  details: password
        "420":
          description: Authentication refused (after 3 failed attempts)
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Authentication refused
                  code: 420
                  error_code: 5
                  details: "Last authentication attempt failed, next attempt will\
                    \ be accepted in 52 seconds"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Internal Server Error
                  code: 500
                  error_code: 100
                  details: '''NEWPIN'' must contain at least 2 numbers'
      
  /api/unlock_pin:
    post:
      operationId: unlock_pin
      tags:
      - Token
      summary: UNLOCK PIN
      description: Unlocks the PIN of a locked token.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials_unlockpin'
        required: false
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: true
                error: null
        "401":
          description: Invalid password
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Invalid credentials
                  code: 401
                  error_code: 1
                  details: ""
        "403":
          description: Invalid `username` or `puk`
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Token not found
                  code: 403
                  error_code: 2
                  details: ""
        "412":
          description: Missing parameter in JSON object
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Missing parameter
                  code: 412
                  error_code: 6
                  details: password
        "420":
          description: Authentication refused (after 3 failed attempts)
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Authentication refused
                  code: 420
                  error_code: 5
                  details: "Last authentication attempt failed, next attempt will\
                    \ be accepted in 52 seconds"
      
  /api/get_objects:
    post:
      operationId: get_objects
      tags:
      - Token
      summary: GET OBJECTS
      description: Retrieves the public key or the certificate of a specified SignCloud
        account.
      requestBody:
        description: JSON object that includes the user credentials for verification.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials_getobjects'
        required: false
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      data:
                        type: string
                      type:
                        type: number
                      ckaid:
                        type: string
                      label:
                        type: string
                    description: The result JSON object
                  error:
                    type: boolean
                    description: The request error key
              example:
                result:
                - data: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArG9kf4t5lIRC96PfuhKGi0CmdCqUxYb3VstbwkvVdmSUBWm+OV1RzhSAR7BxP67e+5VsqKRN+PD273gA676xHIP1VDvrLmX3eOGqq6h3hpU+mQHQ8hzhONyv/uEDmF4ooJXh+zEjfGce/8K42VcMHmMrqj2GRQoyRmX02m95XiY8VMP7mqp5kmDHGQkWsDtJBKhXqMac4GbO8+yiw6MwR2xGhESxS09aaRjqp4bjvRMfFuNSZQL7/2jNufGbU+CBpnxrOoN+AP+vPOIhgXPlEC8Qk6POdKG9FHKLXVtz4DvPeHKyQ+MVbErjVyhK8fTOaR3BnZ+0bGHFf2AovRVfUwIDAQAB
                  type: 3
                  ckaid: DS0
                  label: DS0_PublicKey
                - data: MIIIATCCBemgAwIBAgIIKKcLpQYyugcwDQYJKoZIhvcNAQELBQAwgb0xCzAJBgNVBAYTAkVTMUQwQgYDVQQHDDtCYXJjZWxvbmEgKHNlZSBjdXJyZW50IGFkZHJlc3MgYXQgd3d3LnVhbmF0YWNhLmNvbS9hZGRyZXNzKTEWMBQGA1UECgwNVUFOQVRBQ0EgUy5BLjEUMBIGA1UECwwLQUMtVUFOQVRBQ0ExIDAeBgNVBAMMF1VBTkFUQUNBIENBMSBERVZFTCAyMDE2MRgwFgYDVQRhDA9WQVRFUy1BNjY3MjE0OTkwHhcNMjAxMjAxMTQ1MjAwWhcNMjIxMjAxMTQ1MjAwWjCBpTELMAkGA1UEBhMCRVMxLDAqBgNVBAsMI0pvbmFzIEdvbnphbGV6IERQUjp3d3cudWFuYXRhY2EuY29tMRswGQYDVQQEDBJQcsOhY3RpY2FzIFBydWViYXMxDjAMBgNVBCoMBUpvbmFzMRgwFgYDVQQFEw9JRENFUy1ZMzY0Njk1N0UxITAfBgNVBAMMGEpvbmFzIFByw6FjdGljYXMgUHJ1ZWJhczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKxvZH+LeZSEQvej37oShotApnQqlMWG91bLW8JL1XZklAVpvjldUc4UgEewcT+u3vuVbKikTfjw9u94AOu+sRyD9VQ76y5l93jhqquod4aVPpkB0PIc4Tjcr/7hA5heKKCV4fsxI3xnHv/CuNlXDB5jK6o9hkUKMkZl9NpveV4mPFTD+5qqeZJgxxkJFrA7SQSoV6jGnOBmzvPsosOjMEdsRoREsUtPWmkY6qeG470THxbjUmUC+/9ozbnxm1PggaZ8azqDfgD/rzziIYFz5RAvEJOjznShvRRyi11bc+A7z3hyskPjFWxK41coSvH0zmkdwZ2ftGxhxX9gKL0VX1MCAwEAAaOCAxkwggMVMIHXBggrBgEFBQcBAQSByjCBxzBVBggrBgEFBQcwAoZJaHR0cDovL3d3dy51YW5hdGFjYS5jb20vcHVibGljL2Rvd25sb2FkL3RzcF9jZXJ0aWZpY2F0ZXMvc3Vib3JkaW5hdGUxLmNydDA2BggrBgEFBQcwAYYqaHR0cDovL29jc3AxLnVhbmF0YWNhLmNvbS9wdWJsaWMvcGtpL29jc3AvMDYGCCsGAQUFBzABhipodHRwOi8vb2NzcDIudWFuYXRhY2EuY29tL3B1YmxpYy9wa2kvb2NzcC8wHQYDVR0OBBYEFLn/HGQM26X2iyrzB+XqvAb3/YjAMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUysyKpc+kjCJa1vuX90+0Tv3V764wVQYIKwYBBQUHAQMESTBHMAgGBgQAjkYBATALBgYEAI5GAQMCAQ8wLgYGBACORgEFDCRodHRwczovL3d3dy51YW5hdGFjYS5jb20vcHVibGljL2Nwcy8wga4GA1UdIASBpjCBozBBBgsrBgEEAYLxNgEUBTAyMDAGCCsGAQUFBwIBFiRodHRwczovL3d3dy51YW5hdGFjYS5jb20vcHVibGljL2Nwcy8wXgYLKwYBBAGC8TYBAQUwTzBNBggrBgEFBQcCAjBBDD9DZXJ0aWZpY2FkbyBjdWFsaWZpY2FkbyBkZSBQZXJzb25hIEbDrXNpY2EgZW4gSFNNIGNlbnRyYWxpemFkby4wgY8GA1UdHwSBhzCBhDBAoD6gPIY6aHR0cDovL2NybDEudWFuYXRhY2EuY29tL3B1YmxpYy9wa2kvY3JsL0NBMXN1Ym9yZGluYWRhLmNybDBAoD6gPIY6aHR0cDovL2NybDIudWFuYXRhY2EuY29tL3B1YmxpYy9wa2kvY3JsL0NBMXN1Ym9yZGluYWRhLmNybDAOBgNVHQ8BAf8EBAMCBeAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMCIGA1UdEQQbMBmBF2pvbmFzaXNhaWFzOTlAZ21haWwuY29tMA0GCSqGSIb3DQEBCwUAA4ICAQAeuuN7s8OK8YFaAkRjQY9RoX4onQmxBceLiaKjvXs4Dr/p1sHGyN3nutIMa4JhdPC8wNEy1t3O3nDEfsLdF1LyxSe0CZuHnkMlsr2V8uZXjA4xwwUMEBYwEsGapggN0DuZzDKRC6tkD2q1GkiabfH5UPJs4L1k/zcay549CwZ75K2Me/dommlVIN639oiPw55tByCGH/RtR8CO60PqbiKbW2oPdeIOIfVeaaQDFzTNOoFRT/8snzklm8oGSFjf038vUnNh4VL5wQx2xwe53xKTr9kJar51+u3qq+n6vq4iv1VqUqvvybE3UDr+lnJVjWMNXURl0ZfeVslAHFwQKfO8jGjtX5uq4iRGjcAehs8dgtQ4be+zwoP0XVG/LP/+k+uBmDzGiSOozbrHSkGRkJ+pAU9jUroivk3WeUhGgTM7+e9QCGhcK3eUxR6KSY8JkF2kHd5/Vi258NR2AHyYlRgyg/WyJ0/9rT1Mp57uIOh4N7fLG9qMaBGAlI8Kb5JusfI5nCEoRfyGpQTqOX4jI5glT5UNpdmW/4GSXVYIuA/m0NOqnjD6e4ZOmF/O1PlOSIM4pc4u5aWK79CpqPgyR9fMSXheZoFMrfBX5HTQV8JfWWiO8nXDqFT/HwPdTTyLVgKZYv2hWYL91xMCAePaC24QYgXO+g55r7WB6bPRO3hkAw==
                  type: 4
                  ckaid: DS0
                  label: DS0_Certificate
                error: null
        "401":
          description: Invalid password
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Invalid credentials
                  code: 401
                  error_code: 1
                  details: ""
        "403":
          description: "Invalid `username` , User locked"
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Token locked
                  code: 403
                  error_code: 2
                  details: ""
        "412":
          description: Missing parameter in JSON object
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Missing parameter
                  code: 412
                  error_code: 6
                  details: password
        "420":
          description: Authentication refused (after 3 failed attempts)
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Authentication refused
                  code: 420
                  error_code: 5
                  details: "Last authentication attempt failed, next attempt will\
                    \ be accepted in 52 seconds"
        "500":
          description: Internal Server Error. `identifier` or `mechanism` not supported
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Internal Server Error
                  code: 500
                  error_code: 100
                  details: Mechanism xxxyyy is not supported
     
  /api/token_info:
    post:
      operationId: token_info
      tags:
      - Token
      summary: GET TOKEN INFO
      description: Retrieves the token information of a specified SignCloud account.
        See description of succesful response for more details.
      requestBody:
        description: JSON object that includes the user credentials for verification.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials_tokeninfo'
        required: false
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      puk_counter:
                        type: number
                        description: Remaining attempts before PUK lock
                      label:
                        type: string
                        description: Identifying label
                      qualified:
                        type: string
                        description: Signature level. Qualified signature level requires
                          an OTP code.
                      pin_counter:
                        type: number
                        description: Remaining attempts before PIN lock
                      identifier:
                        type: string
                        description: SignCloud account username
                      webunlock:
                        type: boolean
                        description: Capability to unlock the token through web recovery
                    description: The result JSON object
                  error:
                    type: boolean
                    description: The request error key
              example:
                result:
                  puk_counter: 3
                  label: xxxxxx_Label
                  qualified: true
                  pin_counter: 3
                  identifier: xxxxxx
                  webunlock: true
                error: null
        "401":
          description: Invalid Credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result value
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Invalid credentials
                  code: 401
                  error_code: 1
                  details: ""

  /api/generate_otp:
    post:
      operationId: generate_otp
      tags:
      - RSA
      summary: OTP
      description: Generates an otp for the specified digital identity.</br> <html><blockquote
        style='background-color:#faf3ac; border-color:#DFDFDF; color:#3b3b3b;'><b>⚠This
        method is only required and available for specific digital identities</b></blockquote></html>
      requestBody:
        description: JSON object that includes the user credentials for verification.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials_generateotp'
        required: false
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              example:
                result:
                  identifier: ""
                  additional_data:
                    max_uses: 10000
                    qualified: true
                    number: ""
                    webunlock: true
                error: null

  /api/sign_rsa:
    post:
      operationId: sign_rsa
      tags:
      - RSA
      summary: SIGN RSA
      description: Signs a base64 encoded buffer.
      requestBody:
        description: JSON object that includes the user credentials for verification.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials_signrsa'
        required: false
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: iaJp+O8CxSOPlPL4Eg4KBnlXDG+6g16wgp4ihVLIu3tJDIWFUFUHNgF/8+R1x3TJg4dCpKk6h3Tf+PapnJjGBgxnLeIA5nvdvKFu99Zlm0mS0Y6yjy6wMCEocWFtV+UBVpgXeDHae3XuiSHFu8c9TM7zdlnfmPRkZNHlb+HgafczuMAOfVsPepYsI4qlFIjS76v/6IczeGHV/aeSOa24jyNQsuVgBmbhHqqB8XQS9hHf+rQhvAgFv1o35HRgVDoNr93lkTflT88cjY+ip8ndc2QyY2nuuZmE4OR0ElGUV+9h+6/HMpl0hkHTX/NGRSdipHnZ93bNAahRRVK4okQLRQ==
                error: null
        "401":
          description: Invalid password
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Invalid credentials
                  code: 401
                  error_code: 1
                  details: ""
        "403":
          description: "Invalid `username` or `pin` , User locked"
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Token not found
                  code: 403
                  error_code: 2
                  details: ""
        "412":
          description: Missing parameter in JSON object
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Missing parameter
                  code: 412
                  error_code: 6
                  details: billing_username
        "420":
          description: Authentication refused (after 3 failed attempts)
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Authentication refused
                  code: 420
                  error_code: 5
                  details: "Last authentication attempt failed, next attempt will\
                    \ be accepted in 52 seconds"
        "500":
          description: Internal Server Error. Wrong `identifier` or `mechanism` or
            `billing_username` or `billing_password`
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Internal Server Error
                  code: 500
                  error_code: 100
                  details: Invalid billing credentials
    
  /api/decrypt_rsa:
    post:
      operationId: decrypt_rsa
      tags:
      - RSA
      summary: DECRYPT RSA
      description: Decrypts a base64 buffer.
      requestBody:
        description: JSON object that includes the user credentials for verification.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials_decryptrsa'
        required: false
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: Decrypted output
                error: null
        "401":
          description: Invalid password
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Invalid credentials
                  code: 401
                  error_code: 1
                  details: ""
        "403":
          description: User locked or Invalid `username` or `pin`
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Invalid Pin
                  code: 403
                  error_code: 2
                  details: ""
        "420":
          description: Authentication refused (after 3 failed attempts)
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Authentication refused
                  code: 420
                  error_code: 5
                  details: "Last authentication attempt failed, next attempt will\
                    \ be accepted in 52 seconds"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: The request result key
                  error:
                    type: object
                    properties:
                      msg:
                        type: string
                      code:
                        type: number
                      error_code:
                        type: number
                      details:
                        type: string
                    description: The error JSON object
              example:
                result: null
                error:
                  msg: Internal Server Error
                  code: 500
                  error_code: 100
                  details: DecryptFailed
      
components:
  schemas:
    Credentials:
      required:
      - password
      - pin
      - username
      type: object
      properties:
        username:
          type: string
          description: SignCloud account username
        password:
          type: string
          description: SignCloud account password
        pin:
          type: string
          description: SignCloud account PIN
    Credentials_changepin:
      required:
      - newpin
      - password
      - pin
      - username
      type: object
      properties:
        username:
          type: string
          description: SignCloud account username
        password:
          type: string
          description: SignCloud account password
        pin:
          type: string
          description: SignCloud account PIN
        newpin:
          type: string
          description: The new SignCloud account PIN
    Credentials_unlockpin:
      required:
      - newpin
      - password
      - puk
      - username
      type: object
      properties:
        username:
          type: string
          description: SignCloud account username
        password:
          type: string
          description: SignCloud account password
        newpin:
          type: string
          description: The new SignCloud account PIN
        puk:
          type: string
          description: The token PUK
    Credentials_getobjects:
      required:
      - identifier
      - password
      - type
      - username
      type: object
      properties:
        username:
          type: string
          description: SignCloud account username
        password:
          type: string
          description: SignCloud account password
        type:
          type: string
          description: "The object type. Allowed values are: PublicKey = 3; Certificate\
            \ = 4; Both = null"
          enum:
          - "null"
          - "3"
          - "4"
        identifier:
          type: string
          description: Identifier of the pair of keys. Null value retrieves all the
            objects that the token contains.
          default: DS0
          enum:
          - DS0
          - DS1
          - "null"
    Credentials_tokeninfo:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
          description: SignCloud account username
        password:
          type: string
          description: SignCloud account password
    Credentials_generateotp:
      required:
      - password
      - username
      - uses
      type: object
      properties:
        username:
          type: string
          description: SignCloud account username
        password:
          type: string
          description: SignCloud account password
        uses:
          type: number
          description: Given uses to OTP
    Credentials_signrsa:
      required:
      - billing_password
      - billing_username
      - identifier
      - mechanism
      - otp
      - password
      - pin
      - plaintext
      - username
      type: object
      properties:
        username:
          type: string
          description: SignCloud account username
        password:
          type: string
          description: SignCloud account password
        pin:
          type: string
          description: SignCloud account PIN
        identifier:
          type: string
          description: Identifier of the pair of keys
          default: DS0
        mechanism:
          type: string
          description: "Algorithm used for signing. Supported algorithms are: RSAMD5;\
            \ RSASHA1; RSASHA256; RSASHA512; RSARAW;"
        plaintext:
          type: string
          description: Base64 encoded buffer for signing
        billing_username:
          type: string
          description: Billing account username
        billing_password:
          type: string
          description: Billing account password
        otp:
          type: string
          description: |-
            The OTP code previously sent to the user.
             **This parameter is only required and available for specific digital identities**
    Credentials_decryptrsa:
      required:
      - ciphertext
      - identifier
      - password
      - pin
      - username
      type: object
      properties:
        username:
          type: string
          description: SignCloud account username
        password:
          type: string
          description: SignCloud account password
        pin:
          type: string
          description: SignCloud account PIN
        identifier:
          type: string
          description: Identifier of the pair of keys
          default: DS0
        ciphertext:
          type: string
          description: Text to decrypt
